name: Custom Vanilla Desktop # Replace this name with your image name
id: niffirgkcaj-image # Replace this ID with your image ID
stages:
  - id: build
    base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
    singlelayer: false
    labels:
      maintainer: NiffirgkcaJ # Optionally, Replace this with your name
    args:
      DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
    # Commands to run first before building the modules
    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
    modules:
      - name: init-setup
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update
      - name: install-tools
        type: shell
        commands:
          - apt install -y curl wget git gpg sudo
      - name: add-debian-keys-and-repos
        type: shell
        commands:
          - wget -qO- https://ftp-master.debian.org/keys/archive-key-12-security.asc | gpg --dearmor | sudo tee /usr/share/keyrings/debian-archive-key-12-security.gpg > /dev/null
          - wget -qO- https://ftp-master.debian.org/keys/archive-key-12.asc | gpg --dearmor | sudo tee /usr/share/keyrings/debian-archive-key-12.gpg > /dev/null
          - wget -qO- https://ftp-master.debian.org/keys/release-12.asc | gpg --dearmor | sudo tee /usr/share/keyrings/debian-release-12.gpg > /dev/null
          - echo "deb [signed-by=/usr/share/keyrings/debian-release-12.gpg] http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list.d/debian-bookworm.list
          - echo "deb [signed-by=/usr/share/keyrings/debian-archive-key-12-security.gpg] http://security.debian.org/debian-security bookworm-security main contrib non-free" | sudo tee -a /etc/apt/sources.list.d/debian-bookworm.list
          - echo "deb [signed-by=/usr/share/keyrings/debian-archive-key-12.gpg] http://deb.debian.org/debian/ bookworm-updates main contrib non-free" | sudo tee -a /etc/apt/sources.list.d/debian-bookworm.list
          - echo "deb [signed-by=/usr/share/keyrings/debian-archive-key-12.gpg] http://deb.debian.org/debian/ bookworm-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list.d/debian-bookworm.list
          - echo "deb [signed-by=/usr/share/keyrings/debian-archive-key-12.gpg] http://deb.debian.org/debian/ bookworm-proposed-updates main contrib non-free" | sudo tee -a /etc/apt/sources.list.d/debian-bookworm.list
          - |
            echo 'Package: *' | sudo tee /etc/apt/preferences.d/debian \
            && echo 'Pin: origin deb.debian.org' | sudo tee -a /etc/apt/preferences.d/debian \
            && echo 'Pin-Priority: 100' | sudo tee -a /etc/apt/preferences.d/debian \
            && echo '' | sudo tee -a /etc/apt/preferences.d/debian \
            && echo 'Package: *' | sudo tee -a /etc/apt/preferences.d/debian \
            && echo 'Pin: origin security.debian.org' | sudo tee -a /etc/apt/preferences.d/debian \
            && echo 'Pin-Priority: 100' | sudo tee -a /etc/apt/preferences.d/debian
      - name: add-cloudflarewarp-keys-and-repo
        type: shell
        commands:
          - curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          - echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ bookworm main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
      - name: add-firefox-keys-and-repo
        type: shell
        commands:
          - sudo install -d -m 0755 /etc/apt/keyrings
          - wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
          - echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
          - |
            echo 'Package: *' | sudo tee /etc/apt/preferences.d/mozilla \
            && echo 'Pin: origin packages.mozilla.org' | sudo tee -a /etc/apt/preferences.d/mozilla \
            && echo 'Pin-Priority: 1000' | sudo tee -a /etc/apt/preferences.d/mozilla
      - name: add-firefoxpwa-keys-and-repo
        type: shell
        commands:
          - curl -fsSL https://packagecloud.io/filips/FirefoxPWA/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/firefoxpwa-keyring.gpg > /dev/null
          - echo "deb [signed-by=/usr/share/keyrings/firefoxpwa-keyring.gpg] https://packagecloud.io/filips/FirefoxPWA/any any main" | sudo tee /etc/apt/sources.list.d/firefoxpwa.list > /dev/null
      - name: add-steam-keys-and-repo
        type: shell
        commands:
          - wget -qO- https://repo.steampowered.com/steam/archive/stable/steam.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/steam.gpg > /dev/null
          - echo "deb [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https://repo.steampowered.com/steam/ stable steam" | sudo tee /etc/apt/sources.list.d/steam.list
      - name: enable-32bit-support
        type: shell
        commands:
          - sudo dpkg --add-architecture i386
      - name: update-repositories
        type: shell
        commands:
          - apt-get update
          - sudo apt dist-upgrade
          - sudo apt-get install -f
      - name: install-dependencies
        type: apt
        source:
          packages:
            - libc6-i386
            - libc6:i386=2.36-9+deb12u8
            - libdrm2:i386
            - libgcc-s1:i386
            - libidn2-0:i386
        options:
          noRecommends: false
          installSuggestions: true
          fixMissing: true
          fixBroken: true
      - name: install-applications
        type: apt
        source:
          packages:
            - cloudflare-warp
            - firefox
            - firefoxpwa
            - gparted
            - persepolis
            - steam
        options:
          noRecommends: false
          installSuggestions: true
          fixMissing: true
          fixBroken: true
      - name: add-gnome-customizations
        type: shell
        commands:
          - cd GNOME-Customizations
          - chmod +x install.sh
          - ./install.sh
          - cd ../
          - rm -rf GNOME-Customizations
          - echo "GNOME-Customizations folder deleted."
      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/80-set-image-abroot-config.yml
      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock
      - name: fsguard
        type: fsguard
        CustomFsGuard: false
        FsGuardLocation: "/usr/sbin/FsGuard"
        GenerateKey: true
        FilelistPaths: ["/usr/bin"]
        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init
      - name: cleanup2
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
          - rm -rf /sources
